<!-- colors -->
<!ENTITY color_white "rgb(255,255,255)">

<!-- cycleways -->
<!ENTITY color_ncn "rgb(255,0,255)">
<!ENTITY color_rcn "rgb(255,0,255)">
<!ENTITY color_lcn "rgb(255,0,255)">
<!ENTITY color_ncn_text '#ff8888'>
<!ENTITY color_rcn_text '#88d4ff'>
<!ENTITY color_lcn_text '#6e6eff'>
<!ENTITY color_cycleway_background_text '#000000'>
<!ENTITY color_cycleway_background_text_proposed '#666666'>
<!ENTITY color_cycleway 'rgb(255,17,255)'>
<!ENTITY color_mtb_track 'rgb(113,0,104)'>

<!-- hiking tracks -->
<!ENTITY color_kct_yellow 'rgb(248,238,0)'>
<!ENTITY color_kct_red 'rgb(238,0,0)'>
<!ENTITY color_kct_blue 'rgb(0,0,221)'>
<!ENTITY color_kct_green 'rgb(0,221,0)'>
<!ENTITY color_kct_international 'rgb(238,0,0)'>

<!ENTITY color_footway "rgb(218, 151, 146)">
<!ENTITY color_steps "&color_footway;">

<!ENTITY color_bridleway_fill "rgb(116,64,44)">
<!ENTITY color_track_fill "rgb(72,72,72)">
<!ENTITY color_track_casing "rgb(255,255,255)">
<!ENTITY color_track_tunnel "rgb(128,128,128)">
<!ENTITY color_track_lozoom "rgb(72,72,72)">

<!ENTITY color_bicycle_track_fill "#bb8a4b">
<!ENTITY color_bicycle_track_casing "rgb(255,255,255)">
<!ENTITY color_bicycle_track_tunnel "rgb(128,128,128)">
<!ENTITY color_bicycle_track_lozoom "rgb(72,72,72)">

<!ENTITY color_bicycle '#ff9207'>
<!ENTITY color_bicycle_footway '#d68d30'>

<!ENTITY color_bicycle_tunnel "rgb(75,75,128)">
<!ENTITY color_bicycle_footway_tunnel "rgb(108,75,129)">

<!-- highway-roads -->
<!ENTITY color_oneway_arrow 'rgb(108,112,213)'>
<!ENTITY color_residential_casing '#ffffff'>
<!ENTITY color_residential_fill '#ffffff'>

<!ENTITY color_road 'rgb(180,180,180)'>
<!ENTITY color_residential 'rgb(255,255,255)'>
<!ENTITY color_tertiary 'rgb(255,255,253)'>
<!ENTITY color_secondary 'rgb(252,252,181)'>
<!ENTITY color_primary 'rgb(254,255,107)'>
<!ENTITY color_motorway 'rgb(252,152,53)'>

<!ENTITY color_road_tunnel 'rgb(150,150,150)'>
<!ENTITY color_residential_tunnel 'rgb(255,255,255)'>
<!ENTITY color_tertiary_tunnel 'rgb(231,231,231)'>
<!ENTITY color_secondary_tunnel 'rgb(236,189,128)'>
<!ENTITY color_primary_tunnel 'rgb(204,205,83)'>
<!ENTITY color_motorway_tunnel 'rgb(224,139,56)'>

<!ENTITY color_pedestrian_background 'rgb(128,128,128)'>
<!ENTITY color_road_background '&color_residential_background;'>
<!ENTITY color_residential_background 'rgb(120,120,120)'>
<!ENTITY color_tertiary_background 'rgb(120,120,120)'>
<!ENTITY color_secondary_background 'rgb(163,123,72)'>
<!ENTITY color_primary_background 'rgb(141,67,70)'>
<!ENTITY color_motorway_background 'rgb(80,96,119)'>

<!ENTITY color_lozoom '#606060'>
<!ENTITY color_residential_lozoom '&color_lozoom;'>
<!ENTITY color_tertiary_lozoom '&color_lozoom;'>
<!ENTITY color_secondary_lozoom '&color_lozoom;'>
<!ENTITY color_primary_lozoom '&color_lozoom;'>

<!ENTITY color_pedestrian "rgb(237,237,237)">
<!ENTITY color_pedestrian_bicycle "rgb(212,212,255)">

<!ENTITY color_raceway "rgb(255,192,203)">

<!ENTITY color_tram "rgb(90,90,90)">
<!ENTITY color_railway "rgb(75,75,75)">

<!ENTITY color_non_bicycle_amenity '#6f6f6f'>
<!ENTITY color_bicycle_amenity '#c800da'>

<!ENTITY color_bicycle_shop '&color_bicycle_amenity;'>
<!ENTITY color_police '&color_bicycle_amenity;'>
<!ENTITY color_camp_site 'rgb(0,102,255)'>
<!ENTITY color_bicycle_directions '&color_bicycle_amenity;'>

<!ENTITY color_cycleway_directions 'black'>

<!ENTITY color_food '&color_non_bicycle_amenity;'>
<!ENTITY color_culture '&color_non_bicycle_amenity;'>
<!ENTITY color_embasy '&color_non_bicycle_amenity;'>
<!ENTITY color_accomodation '&color_non_bicycle_amenity;'>
<!ENTITY color_prison '&color_non_bicycle_amenity;'>
<!ENTITY color_fire_station '&color_non_bicycle_amenity;'>
<!ENTITY color_caravan_site '&color_non_bicycle_amenity;'>
<!ENTITY color_parking '&color_non_bicycle_amenity;'>

<!ENTITY color_pharmacy '#47e01b'>

<!ENTITY color_attraction 'rgb(102,0,51)'>

<!ENTITY color_forest 'rgb(181,219,160)'>
<!ENTITY color_wood 'rgb(141,194,124)'>
<!ENTITY color_grass 'rgb(235,249,180)'>
<!ENTITY color_park 'rgb(205,253,194)'>

<!ENTITY color_building 'rgb(188,169,169)'>

<!ENTITY color_placenames_text 'rgb(0,0,0)'>
<!ENTITY color_countries_text 'rgb(157,108,157)'>

<!ENTITY color_glacier 'rgb(153,204,255)'>
<!ENTITY color_water_fill 'rgb(114,155,249)'>
<!ENTITY color_water_stroke 'rgb(80,109,177)'>
<!ENTITY color_island 'rgb(242,239,233)'>
<!ENTITY color_water_weir 'rgb(170,170,170)'>
<!ENTITY color_water_fill_tunnel 'rgb(255,255,255)'>
<!ENTITY color_water_text 'rgb(80,109,177)'>

<!ENTITY opacity_cycleway '0.6'>

<!ENTITY width_track_fill '2'>
<!ENTITY width_track_casing '3'>
<!ENTITY width_track_fill_lozoom '0.6'>
<!ENTITY width_track_casing_lozoom '1'>
