<!-- Style for yellow hiking tracks. -->
<Style name="osmc-track0">
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom10;
    &minscale_zoom10;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">2</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol0] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">3</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>
<Style name="osmc-track1">
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">4</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol1] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">7</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<Style name="osmc-track2">
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">6</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">9</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol2] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">11</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>
<Style name="osmc-track3">
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">-8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">-12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = -1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">-15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="červená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'red:white:red_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_red;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="modrá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'blue:white:blue_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_blue;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="zelená turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'green:white:green_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_green;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">bevel</CssParameter>
      <CssParameter name="stroke-linecap">butt</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_bar')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom11;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-offset">8</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom12;
    &minscale_zoom14;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-offset">12</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 5</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule title="žlutá turistická trasa tečkovaná">
    <Filter>(([offsetside] = 1) and [osmcsymbol3] = 'yellow:white:yellow_dot')</Filter>
    &maxscale_zoom15;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">&color_white;</CssParameter>
      <CssParameter name="stroke-opacity">0.7</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">&color_kct_yellow;</CssParameter>
      <CssParameter name="stroke-opacity">1</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-offset">15</CssParameter>
      <CssParameter name="stroke-linejoin">round</CssParameter>
      <CssParameter name="stroke-linecap">round</CssParameter>
      <CssParameter name="stroke-dasharray">1, 7</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>
