<!-- Style for yellow hiking tracks. -->
<Style name="yellow-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks. -->
<Style name="red-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for green hiking tracks. -->
<Style name="green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for blue hiking tracks. -->
<Style name="blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with red ones. -->
<Style name="yellow-red-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green ones. -->
<Style name="yellow-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with blue ones. -->
<Style name="yellow-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with green ones. -->
<Style name="red-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with blue ones. -->
<Style name="red-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for green hiking tracks together with blue ones. -->
<Style name="green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for red hiking tracks together with green and blue ones. -->
<Style name="red-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,8,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green and blue ones. -->
<Style name="yellow-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,8,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with red and blue ones. -->
<Style name="yellow-red-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,8,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for yellow hiking tracks together with green and blue ones. -->
<Style name="yellow-red-green-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,8,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

<!-- Style for all four hiking tracks together. -->
<Style name="yellow-red-green-blue-track">
  <Rule>
    &maxscale_zoom9;
    &minscale_zoom9;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">1,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,1,1,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,1,1</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">1</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,1,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom10;
    &minscale_zoom11;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">2,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,2,2,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,2,2</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,2,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom12;
    &minscale_zoom12;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">3,9</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,3,3,6</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">2</CssParameter>
      <CssParameter name="stroke-dasharray">0,6,3,3</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">3</CssParameter>
      <CssParameter name="stroke-dasharray">0,9,3,0</CssParameter>
    </LineSymbolizer>
  </Rule>
  <Rule>
    &maxscale_zoom13;
    &minscale_zoom18;
    <LineSymbolizer>
      <CssParameter name="stroke">#dddd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">4,12</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#dd0000</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,4,4,8</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#00dd00</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,8,4,4</CssParameter>
    </LineSymbolizer>
    <LineSymbolizer>
      <CssParameter name="stroke">#0000dd</CssParameter>
      <CssParameter name="stroke-opacity">0.6</CssParameter>
      <CssParameter name="stroke-width">4</CssParameter>
      <CssParameter name="stroke-dasharray">0,12,4,0</CssParameter>
    </LineSymbolizer>
  </Rule>
</Style>

